name: ACR Push Workflow
on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.REGISTRY_LOGIN_SERVER }}/webapp:${{ github.sha }}

jobs:
    build-and-deploy:
        
        runs-on: ubuntu-latest
        
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - run: docker build . -t ${{ env.IMAGE_NAME }}
        - run: docker push ${{ env.IMAGE_NAME }}


