name: ACR Push Workflow
on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.REGISTRY_LOGIN_SERVER }}/dockertest:${{ github.sha }}

jobs:
    build-and-deploy:
        
        runs-on: ubuntu-latest
        
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - run: docker build . -t ${{ env.IMAGE_NAME }}

        - name: Container image scan
          uses: Azure/container-scan@v0.1
          with:
            image-name: ${{ env.IMAGE_NAME }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - run: docker push ${{ env.IMAGE_NAME }}

